### ISSUE TITLE
Download the detected boundary coordinates

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/S_CellDetect_Stardist_HE_ROI#3]
Hi @geektortoise and @gvincke, 

This algorithm is very useful and it helps us in early detection of cells in a large region, and then we can get the expert collaborator to review the boundaries. However, most of our algorithms are in MATLAB. Is there any way to download the detected boundary coordinates? In the analysis annotations page, only the coordinates of the cell centroids can be downloaded. 

Appreciate any assistance. Thank you in advance.

**Comment by geektortoise** [comment]
Hello, 

Instead of downloaded the csv via the Web UI, you can generate it with the wanted value with a "pre-script" in Python.
You can find an example here : https://github.com/cytomine/Cytomine-python-client/blob/master/examples/get_annotations.py

So with your own generated CSV, you will have some information as WKT location and calculate the boundaries (in the Python script before writing the CSV or after in your MATLAB scripts).

The documentation for the python client is here : https://doc.cytomine.org/Python-client?structure=DataScientists
And we also have a Docker image of it :-)

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

Thank you so much! :) I have successfully tested 'Cytomine-python-client' using the following command:

`python3 test.py --cytomine_host "http://localhost-core" --cytomine_public_key "9b9800a2-4f76-4dd9-b342-31c87df6f7ca" --cytomine_private_key "5145fe2b-59f3-4803-8a0c-0e10b656a311"`

and it returns:
> [2021-03-19 12:16:22,579][INFO] [GET] [currentuser] CURRENT USER - 19130 : JOB[admin ], 2021-03-17 01:38:46:235 | 200 OK
[2021-03-19 12:16:22,587][INFO] [GET] [currentuser] CURRENT USER - 19130 : JOB[admin ], 2021-03-17 01:38:46:235 | 200 OK
[currentuser] CURRENT USER - 19130 : JOB[admin ], 2021-03-17 01:38:46:235

Problem 1: But I cannot run it outside '/Cytomine-python-client/examples' directory.

Then I tried 'get_annotations.py' using the following command:

`python3 get_annotations.py --cytomine_host "http://localhost-core" --cytomine_public_key "9b9800a2-4f76-4dd9-b342-31c87df6f7ca" --cytomine_private_key "5145fe2b-59f3-4803-8a0c-0e10b656a311" –cytomine_id_project "19082" --download_path "/home/admincyto/annotations-from-cytomine/18720.csv"`

Problem 2: It returns:

> [2021-03-19 12:13:42,912][INFO] [GET] [currentuser] CURRENT USER - 19130 : JOB[admin ], 2021-03-17 01:38:46:235 | 200 OK
[2021-03-19 12:13:42,919][ERROR] [GET] [annotation collection] 0 objects | 400 Bad Request (There is no project or image filter. We cannot check acl!)
[annotation collection] 0 objects
Traceback (most recent call last):
  File "get_annotations.py", line 61, in <module>
    f= open(params.download_path+"/"+params.id_project+".csv","w+")
TypeError: must be str, not NoneType

I have 231 analysis annotations under `Job ID: 19082`, and 6 manual annotations. I wonder why it detected '0 objects'. Is there anything I missed here?

**Comment by geektortoise** [comment]
Hello, 

Problem 1 : I'm not a fluent Python developper but I guess you can only run the script inside the folder because if the python client is not installed with the step 3 "Install the Cytomine Python client", it will check the "class" around him. :/


Problem 2 : When I copy/paste the command, I got "–cytomine_id_project" instead of "--cytomine_id_project" (double dash)
This will fix the "TypeError: must be str, not NoneType"

When fixed, you got the  "There is no project " only if it is not the correct id.

**Comment by mizjaggy18** [comment]
Hi @geektortoise!

Problem 1: I did step 3, but nevermind, no problem to work in /example directory at the moment.
 
Problem 2: Silly me! Now Problem 2 solved and I got perfect polygon boundary coordinates, together with alpha, crop & mask folders for the manual annotations. Thanks so much! But there is another problem.

Problem 3: How to download analysis annotations from certain Job ID? If I use Job ID for "--cytomine_id_project", it returns:

> [2021-03-19 16:44:12,352][INFO] [GET] [currentuser] CURRENT USER - 19130 : JOB[admin ], 2021-03-17 01:38:46:235 | 200 OK
[2021-03-19 16:44:12,360][ERROR] [GET] [annotation collection] 0 objects | 404 Not Found (ACL error: domain is null! Unable to process project auth checking)
[annotation collection] 0 objects

**Comment by geektortoise** [comment]
Problem 3:

The --cytomine_id_project" is related to the project, not a job.

You can modify the example to fit your need (or create your own py file). Have you tried to set the showAlgo parameter at True ?

(see https://github.com/cytomine/Cytomine-python-client/blob/master/cytomine/models/annotation.py#L191 )

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

Thank you so much for your assistance! I finally managed to download the analysis annotations. I'm a newbie in Python so it took a while :) Just need to add the following lines:

       annotations.job = params.id_job
       annotations.user = params.id_user
       annotations.showAlgo = True 

I include here the modified codes for others to benefit. I name it as "get_annotations_analysis.log" because I cannot upload ".py" here [get_annotations_analysis.log](https://github.com/cytomine/S_CellDetect_Stardist_HE_ROI/files/6202484/get_annotations_analysis.log). 

Thank you!
